#!/bin/bash

# starts fbterm with background image and fcitx

clear

DIR=$(cd -P -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)
IMAGE=../images/bg/bg2.jpg

echo $DIR
echo -ne "\e[?25l" # hide cursor

fbv -ciuker "$DIR/$IMAGE" << EOF
q
EOF

shift
export FBTERM_BACKGROUND_IMAGE=1
exec fcitx-fbterm-helper -l
